[phases.setup]
nixPkgs = ["nodejs_20", "bun", "openssl"]
[phases.install]
cmds = ["cp -r prisma ./prisma || true", "bun install"]
[phases.build]
cmds = ["bunx prisma@6 generate", "bun run build"]
[start]
cmd = "bun run start"
